# Navigation Links
# Updated for custom theme

main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /publication/
    weight: 20
  - name: Experience
    url: /experience/
    weight: 30
  - name: Blog
    url: /post/
    weight: 40
  - name: Teaching
    url: /teaching/
    weight: 50
