# Site parameters for Sara Weston's website

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Sara Weston'
    description: 'Behavioral scientist turning data into decisions. Associate Professor of Psychology at the University of Oregon.'

# Appearance
appearance:
  mode: light
  color: teal

# Footer
footer:
  copyright:
    notice: 'Â© {year} Sara J Weston. All rights reserved.'
